import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import io from "socket.io-client";
const inter = Inter({ subsets: ["latin"] });
import { Input, Spacer, Button, Container, Text, Loading } from "@nextui-org/react";
import { useEffect, useState } from "react";
import { useRouter } from "next/router";
import Chat from "./chat";

//@ts-ignore
const socket = io.connect("http://localhost:3001");

export default function Home() {
  const router = useRouter();
  const [username, setUsername] = useState("");
  const [room, setRoom] = useState("1234");
  const [showChat, setShowChat] = useState(false);

  const joinRoom = () => {
    if (username !== "" && room !== "") {
      socket.emit("join_room", room);
      setShowChat(true);
      // router.push("/chat");
    }
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      {!showChat ? (
        <div className={styles.container}>
          <div className={styles.signinCard}>
            <Text size='$4xl' weight='bold'>
              Username
            </Text>
            <Spacer y={0.5} />
            <Input
              size='lg'
              onChange={(event) => {
                setUsername(event.target.value);
              }}
              fullWidth
            />
            <Spacer y={1} />
            <Button onClick={joinRoom} size='md' css={{ width: "100%" }}>
              Join Chat
            </Button>
          </div>
        </div>
      ) : (
        <Chat socket={socket} username={username} room={room} />
      )}
    </>
  );
}
